[project]
name = "mathlib"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.13.0.2",
    "httpx>=0.28.1",
    "langchain-mcp-adapters>=0.1.13",
    "mcp[cli]>=1.21.1",
    "requests>=2.32.5",
]
